"use client";
import { FilmsDataProvider } from "@/app/data/FilmsDataProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PeopleDataProvider } from "./data/PeoplDataProvider";
import { Nav } from "@/components/Nav/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <FilmsDataProvider>
      <PeopleDataProvider>
        <html lang="en">
          <body suppressHydrationWarning={true} className={inter.className}>
            <div className="flex">
              <Nav />
              {children}
            </div>
          </body>
        </html>
      </PeopleDataProvider>
    </FilmsDataProvider>
  );
}
